<?php

namespace Ilyasse\BlogBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getComments()
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->innerJoin('c.post', 'p')
            ->addSelect('p')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
