<?php

namespace Ilyasse\BlogBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPosts($page, $nbPerPage)
    {
        $query = $this
            ->createQueryBuilder('p')
            ->where('p.published = 1')
            ->leftJoin('p.categories', 'c')
            ->addSelect('c')
            ->orderBy('p.date', 'DESC')
            ->getQuery()
        ;

        $query->setFirstResult(($page-1) * $nbPerPage);
        $query->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }

    public function getMyPosts($author)
    {
        return $this
            ->createQueryBuilder('p')
            ->where('p.author = :author')
            ->setParameter('author', $author)
            ->leftJoin('p.categories', 'c')
            ->addSelect('c')
            ->orderBy('p.date', 'DESC')
            ->getQuery()
            ->getResult()
            ;
    }

}
